# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile.rb, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{vmserver}
  s.version = "0.3.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sriram Varahan"]
  s.date = %q{2010-08-30}
  s.description = %q{This gem simplifies the interaction of ruby code with VMServer. You need to have VMServer installed and running to use this gem.}
  s.email = %q{sriram.varahan@gmail.com}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    ".gitignore",
     "README.textile",
     "Rakefile.rb",
     "VERSION",
     "doc/classes/VMServer.html",
     "doc/classes/VMServer.src/M000001.html",
     "doc/classes/VMServer.src/M000002.html",
     "doc/classes/VMServer.src/M000003.html",
     "doc/classes/VMServer.src/M000004.html",
     "doc/classes/VMServer.src/M000005.html",
     "doc/classes/VMServer.src/M000006.html",
     "doc/classes/VMServer.src/M000007.html",
     "doc/classes/VMServer.src/M000008.html",
     "doc/classes/VMServer.src/M000009.html",
     "doc/classes/VMServer.src/M000010.html",
     "doc/created.rid",
     "doc/files/Rakefile_rb.html",
     "doc/files/lib/vmserver_rb.html",
     "doc/fr_class_index.html",
     "doc/fr_file_index.html",
     "doc/fr_method_index.html",
     "doc/index.html",
     "doc/rdoc-style.css",
     "lib/vmserver.rb",
     "vmserver.gemspec"
  ]
  s.homepage = %q{http://github.com/sriram/vmserver}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A gem to simplify VMServer handling from ruby}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

